# Generated by Django 5.1.12 on 2025-09-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_pic_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
