# Generated by Django 5.1.12 on 2025-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_description_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_name',
            field=models.CharField(blank=True, help_text='Filename in static/recipes/images/ (e.g., pizza.jpg)', max_length=100),
        ),
    ]
